### PR TITLE
Fix TITLE index and ref

### PR DESCRIPTION
**Pull request by geographika**
ttitle > title

### CODE REVIEW

**Comment by jmckenna** [comment]
thanks @geographika !

**Comment by jmckenna** [comment]
at the moment I'm not sure why Backport didn't work here.  checking...

**Comment by geographika** [comment]
@jmckenna - thanks for the backport setup - was just trying it out.
I'll try and fork the docs repo again, looks like the error was `fatal: repository 'https://github.com/geographika/MapServer-documentation.git/' not found`

**Comment by geographika** [comment]
Looks like the issue is my fork is named `docs` and the bot expects the new name `MapServer-documentation`. Not sure if I have to setup a redirect on my side?

**Comment by jmckenna** [comment]
I can't find that message 'fatal: repository 'https://github.com/geographika/MapServer-documentation.git/' in the Backport logs.

**Comment by jmckenna** [comment]
roger thanks

**Pull request merged**
