### PR TITLE
Document MapCache seeder switch

### PR DESCRIPTION
**Pull request by geographika**
Document the new `-H` switch added in https://github.com/MapServer/mapcache/pull/262 and released in MapCache 1.12

### CODE REVIEW

**Comment by geographika** [comment]
Seems like there is an issue with sphinxemoji==0.2.0?
https://app.travis-ci.com/github/MapServer/MapServer-documentation#L258

**Comment by jmckenna** [comment]
true, thanks, diving in....

**Comment by geographika** [comment]
@jmckenna it could be related to https://gitlab.com/python-devs/importlib_metadata/-/issues/86 but the docs builds are using Python 3.7 and not 3.8 so not sure..

Looks like it could be related to something calling `importlib_metadata`.

**Comment by jmckenna** [comment]
you should be ok now once you merge the latest changes from main into this branch.

**Pull request merged**
