### PR TITLE
Removed dated sections.

### PR DESCRIPTION
**Pull request by sdlime**
Removed sections on changing things by URL (versions < 5), Apache environment variable config (not supported in 8) and any references to ROSA (applets are dead). I'd favor sending users to version-specific documentation to keep things clean.

### CODE REVIEW

**Comment by sdlime** [comment]
@jmckenna or @geographika , what do you think about these changes?

**Comment by jmckenna** [comment]
If you are asking my opinion, it is that we should never remove sections, instead just to make sure that these sections are clearly labelled with a warning or note at beginning marking what version they apply to - feedback from users is that they really appreciate the docs in one place.

**Comment by sdlime** [comment]
I think documentation specific to unsupported versions should be removed. It clutters things up and is confusing.

**Comment by jmckenna** [comment]
This is another case where it will be only me voicing this concern (and coincidentally it will be me maintaining this moving forward).

Please merge this now (and lets move on with our lives - the experienced me doesn't want to argue).

**Review by jmckenna — APPROVED** [review]

**Comment by jmckenna** [comment]
Related: for the 8.0 announcement I made sure that all previous doc versions are available at https://mapserver.org/download.html#docspreviousreleases (some were 404, I made sure they all existed).

Please merge this now.  (I can't merge it here now for some reason)

**Comment by sdlime** [comment]
Merged - it was still in Draft I guess.

**Pull request merged**
